sudo: required

services:
  - docker
  
before_install:
  - docker build -t phpmyadmin .
  - docker run -d -p 80:80 --name phpmyadmin phpmyadmin
  - docker ps -a
  
script:
  - docker ps | grep -q phpmyadmin
